//! In-memory knowledge base of dbx's own settings, shortcuts, toolbar
//! actions and supported databases, generated by `scripts/build-capability-index.ts`
//! (`pnpm build:capability-index`) from the real source definitions. Embedded at
//! compile time (see `build.rs`) so the built-in AI agent can answer "does dbx
//! already support X" without a network call or a second hand-maintained copy.

use std::sync::OnceLock;

use serde::Deserialize;

const CAPABILITY_INDEX_JSON: &str = include_str!(concat!(env!("OUT_DIR"), "/capability_index.json"));

#[derive(Debug, Deserialize)]
struct CapabilityIndexFile {
    entries: Vec<CapabilityEntry>,
}

#[derive(Debug, Deserialize)]
pub struct LocalizedText {
    pub cn: String,
    pub en: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CapabilityEntry {
    pub id: String,
    pub kind: String,
    pub category: String,
    pub title: LocalizedText,
    pub description: LocalizedText,
    #[serde(default)]
    pub settings_path: Option<String>,
    #[serde(default)]
    pub default_shortcut: Option<String>,
    pub since_version: String,
    #[serde(default)]
    pub aliases: Vec<String>,
}

impl CapabilityEntry {
    fn matches_query(&self, needle: &str) -> bool {
        self.id.to_lowercase().contains(needle)
            || self.title.cn.to_lowercase().contains(needle)
            || self.title.en.to_lowercase().contains(needle)
            || self.description.cn.to_lowercase().contains(needle)
            || self.description.en.to_lowercase().contains(needle)
            || self.category.to_lowercase().contains(needle)
            || self.aliases.iter().any(|alias| alias.to_lowercase().contains(needle))
    }

    /// One compact line: id | title(cn/en) | category | settings path | since version | shortcut | aliases.
    pub fn render_compact(&self) -> String {
        let mut parts = vec![self.id.clone(), format!("{}/{}", self.title.cn, self.title.en), self.category.clone()];
        if let Some(path) = &self.settings_path {
            parts.push(path.clone());
        }
        parts.push(self.since_version.clone());
        if let Some(shortcut) = &self.default_shortcut {
            parts.push(shortcut.clone());
        }
        if !self.aliases.is_empty() {
            parts.push(format!("别名/aliases: {}", self.aliases.join("/")));
        }
        parts.join(" | ")
    }

    /// Full record including descriptions, for a small, high-confidence result set.
    pub fn render_full(&self) -> String {
        let mut lines = vec![
            format!("- id: {}", self.id),
            format!("  title: {} / {}", self.title.cn, self.title.en),
            format!("  category: {}", self.category),
        ];
        if !self.description.cn.is_empty() || !self.description.en.is_empty() {
            lines.push(format!("  description: {} / {}", self.description.cn, self.description.en));
        }
        if let Some(path) = &self.settings_path {
            lines.push(format!("  settingsPath: {path}"));
        }
        lines.push(format!("  sinceVersion: {}", self.since_version));
        if let Some(shortcut) = &self.default_shortcut {
            lines.push(format!("  defaultShortcut: {shortcut}"));
        }
        if !self.aliases.is_empty() {
            lines.push(format!("  aliases: {}", self.aliases.join(", ")));
        }
        lines.join("\n")
    }
}

fn index() -> &'static [CapabilityEntry] {
    static INDEX: OnceLock<Vec<CapabilityEntry>> = OnceLock::new();
    &INDEX.get_or_init(|| {
        serde_json::from_str::<CapabilityIndexFile>(CAPABILITY_INDEX_JSON)
            .expect("capability_index.json must be valid")
            .entries
    })[..]
}

/// Above this many keyword matches, the result is not narrow enough to be worth
/// rendering in full (with descriptions) — fall through to the compact/full-list form.
const MAX_FULL_MATCHES: usize = 20;

/// Search result for a `search_capability` tool call.
pub enum CapabilitySearch {
    /// A small set of entries confidently matching the query keyword, rendered in full.
    Matches(Vec<String>),
    /// No entry matched the keyword closely enough (or no keyword was given) — the
    /// full compact index, so the calling model can still reason over every entry.
    FullIndex(Vec<String>),
}

/// Look up capabilities by a free-text keyword (case-insensitive substring over
/// id/title/description/category/aliases). Falls back to the whole compact index when
/// nothing narrows the result, since 300 entries comfortably fit in a single tool result.
pub fn search(query: Option<&str>) -> CapabilitySearch {
    let needle = query.map(str::trim).filter(|value| !value.is_empty()).map(str::to_lowercase);
    if let Some(needle) = &needle {
        let matches: Vec<&CapabilityEntry> = index().iter().filter(|entry| entry.matches_query(needle)).collect();
        if !matches.is_empty() && matches.len() <= MAX_FULL_MATCHES {
            return CapabilitySearch::Matches(matches.iter().map(|entry| entry.render_full()).collect());
        }
    }
    CapabilitySearch::FullIndex(index().iter().map(CapabilityEntry::render_compact).collect())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn index_loads_and_is_non_empty() {
        assert!(!index().is_empty(), "capability index must not be empty");
    }

    #[test]
    fn search_narrows_to_known_entry() {
        match search(Some("milvus")) {
            CapabilitySearch::Matches(matches) => {
                assert!(matches.iter().any(|entry| entry.contains("milvus")), "expected a milvus match: {matches:?}");
            }
            CapabilitySearch::FullIndex(_) => panic!("expected narrowed matches for 'milvus'"),
        }
    }

    #[test]
    fn search_falls_back_to_full_index_when_nothing_matches() {
        match search(Some("this query matches absolutely nothing in dbx")) {
            CapabilitySearch::FullIndex(entries) => assert!(!entries.is_empty()),
            CapabilitySearch::Matches(_) => panic!("did not expect a match"),
        }
    }

    #[test]
    fn search_without_query_returns_full_index() {
        match search(None) {
            CapabilitySearch::FullIndex(entries) => assert_eq!(entries.len(), index().len()),
            CapabilitySearch::Matches(_) => panic!("did not expect narrowed matches without a query"),
        }
    }
}
