// Generated by ../../scripts/build-capability-index.ts. This file only adds
// a type wrapper — do not hand-edit capabilityIndex.json.
import raw from "./capabilityIndex.json";

export interface CapabilityEntry {
  id: string;
  kind: "setting" | "shortcut" | "toolbar" | "database";
  category: string;
  title: { cn: string; en: string };
  description: { cn: string; en: string };
  settingsPath?: string;
  defaultShortcut?: string;
  sinceVersion: string;
  aliases: string[];
}

export const capabilityIndex: CapabilityEntry[] = (raw as { entries: CapabilityEntry[] }).entries;
